version: '2'
services:
  centos7:
    build: docker/centos7/
    privileged: true
    entrypoint: /usr/lib/systemd/systemd
  jessie64:
    build: docker/jessie64/
    privileged: true
    entrypoint: /lib/systemd/systemd
  trusty64:
    build: docker/trusty64/
    entrypoint: /sbin/init
  xenial64:
    build: docker/xenial64/
    privileged: true
    entrypoint: /sbin/init
