---
- name: retrieve version manifest
  uri:
    url: "{{ minecraft_version_manifest_url }}"
    return_content: true
  register: version_manifest

- name: find and set latest version
  set_fact:
    minecraft_version_latest: "{{ (version_manifest.content | from_json).latest.release }}"
